# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_points', models.IntegerField(blank=True, null=True)),
                ('user2_points', models.IntegerField(blank=True, null=True)),
                ('board', models.TextField(blank=True, null=True)),
                ('board_solved', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_rel', to='sudoku.GameUser'),
        ),
        migrations.AddField(
            model_name='game',
            name='user2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2_rel', to='sudoku.GameUser'),
        ),
    ]
