# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0003_game_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='room',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
