# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0004_gameuser_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='real_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
